spring.application.name=forum_hub

spring.datasource.url=jdbc:postgresql://localhost:5432/forum_hub
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

github.account.username=${GITHUB_EMAIL}}
github.account.client-id=${GITHUB_CLIENT_ID}
github.account.client-secret=${GITHUB_CLIENT_SECRET}
github.account.redirect=http://localhost:8080/login/github/autorizado